branch-defaults:
  master:
    environment: Steroid-example-application-env
environment-defaults:
  Steroid-example-application-env:
    branch: null
    repository: null
global:
  application_name: steroid-example-application
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
